### ISSUE TITLE
fix: Installing version-bump from deno.land throws error

### ISSUE THREAD

**Issue by jhechtf** [jhechtf/version-bump#15]
### Steps to recreation

1. Run `deno install -A -n version-bump --no-check https://deno.land/x/version_bump@0.2.0/cli.ts`.
2. Attempt to run it with `version-bump --firstRelease`
3. Receive the following error
  >  error: Uncaught Error: TypeInfo not known for "Git"
    at r.construct (https://cdn.esm.sh/v77/tsyringe@4.6.0/deno/tsyringe.js:4:6281)
    at r.resolve (https://cdn.esm.sh/v77/tsyringe@4.6.0/deno/tsyringe.js:4:2182)  
    at https://deno.land/x/version_bump@0.2.0/cli.ts:99:23

### Expected behavior

To work.

## Exit Criteria

- [x] Get it to work remotely.

**Comment by jhechtf** [comment]
Okay so some things learned:

1. I was trying to run this command in a repo I had not run any git commands for previously. As such, it had no git repository info to read from.
2. The error message that occurs from that definitely needs to be more clear.

But those are different issues from this, and I will open other tickets for them.

Resolving.
